apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifactory-edge-exporter.fullname" . }}
  labels: {{- include "artifactory-edge-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.exporterConfig | nindent 4 }}
