{{- if .Values.secrets }}
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifactory-edge-exporter.fullname" . }}
  labels:
    {{- include "artifactory-edge-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
{{- end }}
